
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'AlertDialog': typeof import("../components/ui/alert-dialog/index")['AlertDialog']
    'AlertDialogTrigger': typeof import("../components/ui/alert-dialog/index")['AlertDialogTrigger']
    'AlertDialogContent': typeof import("../components/ui/alert-dialog/index")['AlertDialogContent']
    'AlertDialogHeader': typeof import("../components/ui/alert-dialog/index")['AlertDialogHeader']
    'AlertDialogTitle': typeof import("../components/ui/alert-dialog/index")['AlertDialogTitle']
    'AlertDialogDescription': typeof import("../components/ui/alert-dialog/index")['AlertDialogDescription']
    'AlertDialogFooter': typeof import("../components/ui/alert-dialog/index")['AlertDialogFooter']
    'AlertDialogAction': typeof import("../components/ui/alert-dialog/index")['AlertDialogAction']
    'AlertDialogCancel': typeof import("../components/ui/alert-dialog/index")['AlertDialogCancel']
    'Button': typeof import("../components/ui/button/index")['Button']
    'Dialog': typeof import("../components/ui/dialog/index")['Dialog']
    'DialogClose': typeof import("../components/ui/dialog/index")['DialogClose']
    'DialogTrigger': typeof import("../components/ui/dialog/index")['DialogTrigger']
    'DialogHeader': typeof import("../components/ui/dialog/index")['DialogHeader']
    'DialogTitle': typeof import("../components/ui/dialog/index")['DialogTitle']
    'DialogDescription': typeof import("../components/ui/dialog/index")['DialogDescription']
    'DialogContent': typeof import("../components/ui/dialog/index")['DialogContent']
    'DialogScrollContent': typeof import("../components/ui/dialog/index")['DialogScrollContent']
    'DialogFooter': typeof import("../components/ui/dialog/index")['DialogFooter']
    'DropdownMenuPortal': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
    'DropdownMenu': typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
    'DropdownMenuTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
    'DropdownMenuContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
    'DropdownMenuGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
    'DropdownMenuRadioGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
    'DropdownMenuItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
    'DropdownMenuCheckboxItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
    'DropdownMenuRadioItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
    'DropdownMenuShortcut': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
    'DropdownMenuSeparator': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
    'DropdownMenuLabel': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
    'DropdownMenuSub': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
    'DropdownMenuSubTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
    'DropdownMenuSubContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
    'Input': typeof import("../components/ui/input/index")['Input']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page-placeholder")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyAlertDialog': typeof import("../components/ui/alert-dialog/index")['AlertDialog']
    'LazyAlertDialogTrigger': typeof import("../components/ui/alert-dialog/index")['AlertDialogTrigger']
    'LazyAlertDialogContent': typeof import("../components/ui/alert-dialog/index")['AlertDialogContent']
    'LazyAlertDialogHeader': typeof import("../components/ui/alert-dialog/index")['AlertDialogHeader']
    'LazyAlertDialogTitle': typeof import("../components/ui/alert-dialog/index")['AlertDialogTitle']
    'LazyAlertDialogDescription': typeof import("../components/ui/alert-dialog/index")['AlertDialogDescription']
    'LazyAlertDialogFooter': typeof import("../components/ui/alert-dialog/index")['AlertDialogFooter']
    'LazyAlertDialogAction': typeof import("../components/ui/alert-dialog/index")['AlertDialogAction']
    'LazyAlertDialogCancel': typeof import("../components/ui/alert-dialog/index")['AlertDialogCancel']
    'LazyButton': typeof import("../components/ui/button/index")['Button']
    'LazyDialog': typeof import("../components/ui/dialog/index")['Dialog']
    'LazyDialogClose': typeof import("../components/ui/dialog/index")['DialogClose']
    'LazyDialogTrigger': typeof import("../components/ui/dialog/index")['DialogTrigger']
    'LazyDialogHeader': typeof import("../components/ui/dialog/index")['DialogHeader']
    'LazyDialogTitle': typeof import("../components/ui/dialog/index")['DialogTitle']
    'LazyDialogDescription': typeof import("../components/ui/dialog/index")['DialogDescription']
    'LazyDialogContent': typeof import("../components/ui/dialog/index")['DialogContent']
    'LazyDialogScrollContent': typeof import("../components/ui/dialog/index")['DialogScrollContent']
    'LazyDialogFooter': typeof import("../components/ui/dialog/index")['DialogFooter']
    'LazyDropdownMenuPortal': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
    'LazyDropdownMenu': typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
    'LazyDropdownMenuTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
    'LazyDropdownMenuContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
    'LazyDropdownMenuGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
    'LazyDropdownMenuRadioGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
    'LazyDropdownMenuItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
    'LazyDropdownMenuCheckboxItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
    'LazyDropdownMenuRadioItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
    'LazyDropdownMenuShortcut': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
    'LazyDropdownMenuSeparator': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
    'LazyDropdownMenuLabel': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
    'LazyDropdownMenuSub': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
    'LazyDropdownMenuSubTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
    'LazyDropdownMenuSubContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
    'LazyInput': typeof import("../components/ui/input/index")['Input']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page-placeholder")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const AlertDialog: typeof import("../components/ui/alert-dialog/index")['AlertDialog']
export const AlertDialogTrigger: typeof import("../components/ui/alert-dialog/index")['AlertDialogTrigger']
export const AlertDialogContent: typeof import("../components/ui/alert-dialog/index")['AlertDialogContent']
export const AlertDialogHeader: typeof import("../components/ui/alert-dialog/index")['AlertDialogHeader']
export const AlertDialogTitle: typeof import("../components/ui/alert-dialog/index")['AlertDialogTitle']
export const AlertDialogDescription: typeof import("../components/ui/alert-dialog/index")['AlertDialogDescription']
export const AlertDialogFooter: typeof import("../components/ui/alert-dialog/index")['AlertDialogFooter']
export const AlertDialogAction: typeof import("../components/ui/alert-dialog/index")['AlertDialogAction']
export const AlertDialogCancel: typeof import("../components/ui/alert-dialog/index")['AlertDialogCancel']
export const Button: typeof import("../components/ui/button/index")['Button']
export const Dialog: typeof import("../components/ui/dialog/index")['Dialog']
export const DialogClose: typeof import("../components/ui/dialog/index")['DialogClose']
export const DialogTrigger: typeof import("../components/ui/dialog/index")['DialogTrigger']
export const DialogHeader: typeof import("../components/ui/dialog/index")['DialogHeader']
export const DialogTitle: typeof import("../components/ui/dialog/index")['DialogTitle']
export const DialogDescription: typeof import("../components/ui/dialog/index")['DialogDescription']
export const DialogContent: typeof import("../components/ui/dialog/index")['DialogContent']
export const DialogScrollContent: typeof import("../components/ui/dialog/index")['DialogScrollContent']
export const DialogFooter: typeof import("../components/ui/dialog/index")['DialogFooter']
export const DropdownMenuPortal: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
export const DropdownMenu: typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
export const DropdownMenuTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
export const DropdownMenuContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
export const DropdownMenuGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
export const DropdownMenuRadioGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
export const DropdownMenuItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
export const DropdownMenuCheckboxItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
export const DropdownMenuRadioItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
export const DropdownMenuShortcut: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
export const DropdownMenuSeparator: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
export const DropdownMenuLabel: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
export const DropdownMenuSub: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
export const DropdownMenuSubTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
export const DropdownMenuSubContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
export const Input: typeof import("../components/ui/input/index")['Input']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page-placeholder")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyAlertDialog: typeof import("../components/ui/alert-dialog/index")['AlertDialog']
export const LazyAlertDialogTrigger: typeof import("../components/ui/alert-dialog/index")['AlertDialogTrigger']
export const LazyAlertDialogContent: typeof import("../components/ui/alert-dialog/index")['AlertDialogContent']
export const LazyAlertDialogHeader: typeof import("../components/ui/alert-dialog/index")['AlertDialogHeader']
export const LazyAlertDialogTitle: typeof import("../components/ui/alert-dialog/index")['AlertDialogTitle']
export const LazyAlertDialogDescription: typeof import("../components/ui/alert-dialog/index")['AlertDialogDescription']
export const LazyAlertDialogFooter: typeof import("../components/ui/alert-dialog/index")['AlertDialogFooter']
export const LazyAlertDialogAction: typeof import("../components/ui/alert-dialog/index")['AlertDialogAction']
export const LazyAlertDialogCancel: typeof import("../components/ui/alert-dialog/index")['AlertDialogCancel']
export const LazyButton: typeof import("../components/ui/button/index")['Button']
export const LazyDialog: typeof import("../components/ui/dialog/index")['Dialog']
export const LazyDialogClose: typeof import("../components/ui/dialog/index")['DialogClose']
export const LazyDialogTrigger: typeof import("../components/ui/dialog/index")['DialogTrigger']
export const LazyDialogHeader: typeof import("../components/ui/dialog/index")['DialogHeader']
export const LazyDialogTitle: typeof import("../components/ui/dialog/index")['DialogTitle']
export const LazyDialogDescription: typeof import("../components/ui/dialog/index")['DialogDescription']
export const LazyDialogContent: typeof import("../components/ui/dialog/index")['DialogContent']
export const LazyDialogScrollContent: typeof import("../components/ui/dialog/index")['DialogScrollContent']
export const LazyDialogFooter: typeof import("../components/ui/dialog/index")['DialogFooter']
export const LazyDropdownMenuPortal: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
export const LazyDropdownMenu: typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
export const LazyDropdownMenuTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
export const LazyDropdownMenuContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
export const LazyDropdownMenuGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
export const LazyDropdownMenuRadioGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
export const LazyDropdownMenuItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
export const LazyDropdownMenuCheckboxItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
export const LazyDropdownMenuRadioItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
export const LazyDropdownMenuShortcut: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
export const LazyDropdownMenuSeparator: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
export const LazyDropdownMenuLabel: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
export const LazyDropdownMenuSub: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
export const LazyDropdownMenuSubTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
export const LazyDropdownMenuSubContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
export const LazyInput: typeof import("../components/ui/input/index")['Input']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page-placeholder")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
