// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/29/2024, 5:21:33 PM
const configMerger = require("/Users/kinyano/Desktop/ms-kanban-project/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/kinyano/Desktop/ms-kanban-project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kinyano/Desktop/ms-kanban-project/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kinyano/Desktop/ms-kanban-project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kinyano/Desktop/ms-kanban-project/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kinyano/Desktop/ms-kanban-project/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kinyano/Desktop/ms-kanban-project/plugins/**/*.{js,ts,mjs}","/Users/kinyano/Desktop/ms-kanban-project/composables/**/*.{js,ts,mjs}","/Users/kinyano/Desktop/ms-kanban-project/utils/**/*.{js,ts,mjs}","/Users/kinyano/Desktop/ms-kanban-project/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/kinyano/Desktop/ms-kanban-project/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/kinyano/Desktop/ms-kanban-project/app.config.{js,ts,mjs}"] }));

module.exports = config
