// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/29/2024, 12:32:00 AM
const configMerger = require("/Users/kinyano/Desktop/ms-kanban-project/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/kinyano/Desktop/ms-kanban-project/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kinyano/Desktop/ms-kanban-project/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kinyano/Desktop/ms-kanban-project/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kinyano/Desktop/ms-kanban-project/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kinyano/Desktop/ms-kanban-project/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kinyano/Desktop/ms-kanban-project/frontend/plugins/**/*.{js,ts,mjs}","/Users/kinyano/Desktop/ms-kanban-project/frontend/composables/**/*.{js,ts,mjs}","/Users/kinyano/Desktop/ms-kanban-project/frontend/utils/**/*.{js,ts,mjs}","/Users/kinyano/Desktop/ms-kanban-project/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/kinyano/Desktop/ms-kanban-project/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/kinyano/Desktop/ms-kanban-project/frontend/app.config.{js,ts,mjs}"] }));

module.exports = config
